In [1]:
!rm .fleche -rf

# Getting Started with Fleche

This notebook demonstrates the main features of the `fleche` library, a caching library for Python.

## Long-running calculation

In [2]:
import time
from fleche import fleche, cache, tags, project
from fleche.digest import Digest

LOGGING INFO: local config fleche.toml does not exist, trying global
LOGGING INFO: global config /home/jules/.fleche.toml does not exist
Warning: No config file found. Using default memory cache.
LOGGING INFO: local config fleche.toml does not exist, trying global
LOGGING INFO: global config /home/jules/.fleche.toml does not exist

In [3]:
@fleche
def long_running_calculation(x):
    print(f'Running calculation for {x}...')
    time.sleep(2)
    return x * x

In [4]:
start = time.time()
long_running_calculation(2)
end = time.time()
print(f'First call took {end - start:.2f} seconds.')

Running calculation for 2...

First call took 2.00 seconds.

In [5]:
start = time.time()
long_running_calculation(2)
end = time.time()
print(f'Second call took {end - start:.2f} seconds.')

Second call took 0.00 seconds.

As you can see, the second call returns almost instantly, because the result was cached.

## Recursive function

In [6]:
@fleche
def fib(n):
    if n < 2:
        return n
    return fib(n-1) + fib(n-2)

In [7]:
start = time.time()
fib(20)
end = time.time()
print(f'fib(20) took {end - start:.4f} seconds with caching.')

fib(20) took 0.0122 seconds with caching.

Without caching, this would be much slower as each call to `fib` would be recomputed.

## Caching Methods of User-defined Types

`fleche` can also cache methods of classes. For this to work, the class must be "digest-compatible". You can make a class digest-compatible by implementing a `__digest__` method or by using a `dataclass`.

In [8]:
class MyClass:
    def __init__(self, val):
        self.val = val
    
    def __digest__(self):
        # The digest defines how the instance is identified in the cache
        return Digest(str(self.val))

    @fleche
    def compute(self, x):
        print(f"Computing {self.val} + {x}...")
        time.sleep(1)
        return self.val + x

In [9]:
obj = MyClass(10)

start = time.time()
print(f"Result: {obj.compute(5)}")
print(f"First call took {time.time() - start:.2f} seconds.")

start = time.time()
print(f"Result: {obj.compute(5)}")
print(f"Second call (same instance) took {time.time() - start:.2f} seconds.")

Computing 10 + 5...

Result: 15
First call took 1.00 seconds.
Result: 15
Second call (same instance) took 0.00 seconds.

If you mutate the instance such that its digest changes, the cache will be missed.

In [10]:
obj.val = 20
start = time.time()
print(f"Result: {obj.compute(5)}")
print(f"Call after mutation took {time.time() - start:.2f} seconds.")

Computing 20 + 5...

Result: 25
Call after mutation took 1.00 seconds.

## Passing Digests as Arguments

`fleche` supports passing `Digest` objects directly to cached functions. When a function receives a `Digest`, `fleche` automatically expands it to its actual value from the cache before executing the function. You can use the convenience wrapper `D` to mark a string as a digest.

In [11]:
from fleche import D

@fleche
def double(x):
    print(f"Doubling {x}...")
    return x * 2

# 1. Run the calculation to ensure it is cached
long_running_calculation(10)

# 2. Get its digest
digest_10 = long_running_calculation.digest(10)
print(f"Digest: {digest_10}")
# Output: 727c0fb9120f5eca7e0d4e550c6ee8d9019e07c62463b2a8cc7581d6cb8500

# 3. Pass the digest (even a short one!) to double(). It will be expanded to 100.
# Use D() to mark it as a digest.
print(f"Result: {double(D('727c0fb9'))}")

Running calculation for 10...

Digest: 727c0fb9120f5eca7e0d4e550c6ee8d9019e07c62463b2a8cc7581d8b9c700da
Doubling 100...
Result: 200

## Metadata

`fleche` allows you to add metadata to your cached functions using the `tags` context manager. This can be useful for organizing and querying your results.

In [12]:
@fleche
def another_calculation(a, b):
    return a + b

In [13]:
with tags(project='my_project', category='testing'):
    another_calculation(1, 2)
    another_calculation(3, 4)

This metadata is stored alongside the cached result. You can then use the `metadata.table` method to view the metadata for all cached results.

In [14]:
cache().table()

,name,args,kwargs,module,version,result,timestart,timestop,walltime,project,category
0,long_running_calculation,(92a9b214d814a4a7b5f9ba52e2248c6d16ec0196d8cd7...,{},__main__,None,83ada2198553b88cb3d0882f7fca8c4e9531049b978df3...,1.771246e+09,1.771246e+09,2.000444,NaN,NaN
1,fib,(da217d50752f3371d9f8b62a3e72409592bd34b74e14f...,{},__main__,None,da217d50752f3371d9f8b62a3e72409592bd34b74e14fd...,1.771246e+09,1.771246e+09,0.000013,NaN,NaN
2,fib,(26461de90bccabfde78889464de27c40b1a962fdc312a...,{},__main__,None,26461de90bccabfde78889464de27c40b1a962fdc312a7...,1.771246e+09,1.771246e+09,0.000015,NaN,NaN
3,fib,(92a9b214d814a4a7b5f9ba52e2248c6d16ec0196d8cd7...,{},__main__,None,da217d50752f3371d9f8b62a3e72409592bd34b74e14fd...,1.771246e+09,1.771246e+09,0.001268,NaN,NaN
4,fib,(65d52a82c5a72f12ca0499522dc9274a0e6822e103863...,{},__main__,None,92a9b214d814a4a7b5f9ba52e2248c6d16ec0196d8cd77...,1.771246e+09,1.771246e+09,0.002973,NaN,NaN
5,fib,(83ada2198553b88cb3d0882f7fca8c4e9531049b978df...,{},__main__,None,65d52a82c5a72f12ca0499522dc9274a0e6822e1038630...,1.771246e+09,1.771246e+09,0.003490,NaN,NaN
6,fib,(5b07a837d91d67764109c11fb912c9b91b4e9d9d4c909...,{},__main__,None,5b07a837d91d67764109c11fb912c9b91b4e9d9d4c909f...,1.771246e+09,1.771246e+09,0.004014,NaN,NaN
7,fib,(6511a915535857f7e7ca73b8b62968975f357664ed331...,{},__main__,None,08fa94f35017cb4c1e6d1a7edd09503f5f1650b888cbb6...,1.771246e+09,1.771246e+09,0.004507,NaN,NaN
8,fib,(307ea96b8b27c58a4c93e2e34e3783e475dc0e8ef99b4...,{},__main__,None,05c7cb7b6fa10504e50f57bdfb56962669740ee04b34ba...,1.771246e+09,1.771246e+09,0.004920,NaN,NaN
9,fib,(08fa94f35017cb4c1e6d1a7edd09503f5f1650b888cbb...,{},__main__,None,8d211f6913c5bc9a8f36627fdff1cf8ba87a64a9738ab9...,1.771246e+09,1.771246e+09,0.005397,NaN,NaN
10,fib,(3fbaa6084b6274d30f415d688ef2be05c81364296e804...,{},__main__,None,5eff6ff7fcf52aaed447a61cd338eb075ad5ff9157da52...,1.771246e+09,1.771246e+09,0.005858,NaN,NaN
11,fib,(f3f64312ae6c7771851d6d1ab57d134ac193e54640a5c...,{},__main__,None,76fcb1a29d2d832155ceac068d975e94521f1bb4a9215f...,1.771246e+09,1.771246e+09,0.006369,NaN,NaN
12,fib,(a39b3523cb475ef9759518728c1252c18d68eb56b93bd...,{},__main__,None,39909d086dae7dc4753703cf4dd47cdfad6bae38651b67...,1.771246e+09,1.771246e+09,0.007076,NaN,NaN
13,fib,(056a34cfa7662755ef47b05e966a8cd152ad9cd663134...,{},__main__,None,239e59ca67f9ed74f3f30cbb6c25fcf74b8a559fe3fb51...,1.771246e+09,1.771246e+09,0.007560,NaN,NaN
14,fib,(05c7cb7b6fa10504e50f57bdfb56962669740ee04b34b...,{},__main__,None,069f08ed1d86450bc41f14df9221dcbf1ce6e66b1762d6...,1.771246e+09,1.771246e+09,0.008044,NaN,NaN
15,fib,(3201de819be5415cbdafba20084037ae8a7fa4372861f...,{},__main__,None,999818e226e4d8c903d3f26c23711294487280876170f1...,1.771246e+09,1.771246e+09,0.008520,NaN,NaN
16,fib,(4299b052f31ce284d363962dfed96eb3224cbafde29a4...,{},__main__,None,e1814f9e8adf0af339af7981a0717c71ebd9d1dca6f3aa...,1.771246e+09,1.771246e+09,0.009484,NaN,NaN
17,fib,(ab7147c672380ae7a61133670895102a6a22971e1aaae...,{},__main__,None,b3e4a8d2b5f6e5da7cebb7d22a9d418ac58ce610a20b8e...,1.771246e+09,1.771246e+09,0.009906,NaN,NaN
18,fib,(3c6d58fdd5a667db288d091bac0bce502fe0c3d64cbac...,{},__main__,None,ee4fbff3e942b83d7ab79d427409f8204cb1ba71efb122...,1.771246e+09,1.771246e+09,0.010309,NaN,NaN
19,fib,(fb6de151fa90964b97efcca1d839d5d010a1757080dd3...,{},__main__,None,e1cc3d9ddc91d7b45bf07452d45884af82d8787f328cd3...,1.771246e+09,1.771246e+09,0.010764,NaN,NaN
20,fib,(5237ebc7cf43bccd65af14d4d42a551b940faccceac29...,{},__main__,None,bdb771c588d071ded3791c5462b3bc5516c9f93a94ec18...,1.771246e+09,1.771246e+09,0.011273,NaN,NaN
21,fib,(cfa199f81a343060e585229e105a520ba3fd17176df10...,{},__main__,None,306e7d87769d46792e90e843c36e65dc22edbbc96bff87...,1.771246e+09,1.771246e+09,0.011761,NaN,NaN
22,compute,"(10, 5b07a837d91d67764109c11fb912c9b91b4e9d9d4...",{},__main__,None,4299b052f31ce284d363962dfed96eb3224cbafde29a40...,1.771246e+09,1.771246e+09,1.000408,NaN,NaN
23,compute,"(20, 5b07a837d91d67764109c11fb912c9b91b4e9d9d4...",{},__main__,None,7eabebe706259302bd54c2a51fd4350695d9481b4fbf09...,1.771246e+09,1.771246e+09,1.000372,NaN,NaN
24,long_running_calculation,(f3f64312ae6c7771851d6d1ab57d134ac193e54640a5c...,{},__main__,None,60079f7901a9295349d1796c037afc132e81286f785dde...,1.771246e+09,1.771246e+09,2.000346,NaN,NaN
25,double,"(727c0fb9,)",{},__main__,None,0c55ce113e97ef4f8899beb58e9aaffa3fffc56c6b4626...,1.771246e+09,1.771246e+09,0.000247,NaN,NaN
26,another_calculation,(da217d50752f3371d9f8b62a3e72409592bd34b74e14f...,{},__main__,None,65d52a82c5a72f12ca0499522dc9274a0e6822e1038630...,1.771246e+09,1.771246e+09,0.000033,my_project,testing
27,another_calculation,(65d52a82c5a72f12ca0499522dc9274a0e6822e103863...,{},__main__,None,307ea96b8b27c58a4c93e2e34e3783e475dc0e8ef99b4c...,1.771246e+09,1.771246e+09,0.000020,my_project,testing

## Filtering

The metadata table is just pandas so you can query and filter as you like.

In [15]:
cache().table().query('name!="fib"')

,name,args,kwargs,module,version,result,timestart,timestop,walltime,project,category
0,long_running_calculation,(92a9b214d814a4a7b5f9ba52e2248c6d16ec0196d8cd7...,{},__main__,None,83ada2198553b88cb3d0882f7fca8c4e9531049b978df3...,1.771246e+09,1.771246e+09,2.000444,NaN,NaN
22,compute,"(10, 5b07a837d91d67764109c11fb912c9b91b4e9d9d4...",{},__main__,None,4299b052f31ce284d363962dfed96eb3224cbafde29a40...,1.771246e+09,1.771246e+09,1.000408,NaN,NaN
23,compute,"(20, 5b07a837d91d67764109c11fb912c9b91b4e9d9d4...",{},__main__,None,7eabebe706259302bd54c2a51fd4350695d9481b4fbf09...,1.771246e+09,1.771246e+09,1.000372,NaN,NaN
24,long_running_calculation,(f3f64312ae6c7771851d6d1ab57d134ac193e54640a5c...,{},__main__,None,60079f7901a9295349d1796c037afc132e81286f785dde...,1.771246e+09,1.771246e+09,2.000346,NaN,NaN
25,double,"(727c0fb9,)",{},__main__,None,0c55ce113e97ef4f8899beb58e9aaffa3fffc56c6b4626...,1.771246e+09,1.771246e+09,0.000247,NaN,NaN
26,another_calculation,(da217d50752f3371d9f8b62a3e72409592bd34b74e14f...,{},__main__,None,65d52a82c5a72f12ca0499522dc9274a0e6822e1038630...,1.771246e+09,1.771246e+09,0.000033,my_project,testing
27,another_calculation,(65d52a82c5a72f12ca0499522dc9274a0e6822e103863...,{},__main__,None,307ea96b8b27c58a4c93e2e34e3783e475dc0e8ef99b4c...,1.771246e+09,1.771246e+09,0.000020,my_project,testing

In [16]:
cache().table().query('project=="my_project"')

,name,args,kwargs,module,version,result,timestart,timestop,walltime,project,category
26,another_calculation,(da217d50752f3371d9f8b62a3e72409592bd34b74e14f...,{},__main__,None,65d52a82c5a72f12ca0499522dc9274a0e6822e1038630...,1.771246e+09,1.771246e+09,0.000033,my_project,testing
27,another_calculation,(65d52a82c5a72f12ca0499522dc9274a0e6822e103863...,{},__main__,None,307ea96b8b27c58a4c93e2e34e3783e475dc0e8ef99b4c...,1.771246e+09,1.771246e+09,0.000020,my_project,testing